xrdb -load "$XDG_CONFIG_HOME/X11/Xresources" &
setxkbmap -option "caps:swapescape" &
pulseaudio --start &
hsetroot -tile ~/.cache/wall.png &
dunst &
"$XDG_CONFIG_HOME"/polybar/launch-polybar &
exec cwm
