#!/usr/bin/env bash
# Variables to determine what wm the user has installed
bspwm="0"
awesome="0"

# A nice thing to divide stuff into sections
div()
{
	title=$1
	printf "\n\e[1;32m%s\n--------------------\e[0m\n" "$title"
}

askinstall()
{
	thing=$1
	printf "\nDo you want to install \e[1;32m%s\e[0m? [\e[1;32mY\e[0m/\e[31mN\e[0m] " "$thing"
	read -r answer
}

installing()
{
	thing=$1
	printf "\nInstalling \e[1;32m%s\e[0m" "$thing"
}

div "DOTFILES"
# Installing the thing that symlinks the dotfiles, git to get the dotfiles and xorg to have a gui
installing "rcm & git & xorg"
sudo xbps-install -y rcm git xorg >> /dev/null
printf "\n"
# Getting the dotfiles from the git repo
echo "Downloading dotfilkes"
git clone "https://gitlab.com/cha0t1c/dotfiles.git" "$HOME/.dotfiles" >> /dev/null
# Symlinking the dotfiles using rcm
echo "Symlinking dotfiles"
rcup
# Removing some useless stuff from the home directory
rm -r "$HOME/.images" "$HOME/.LICENSE" "$HOME/.README.md" "$HOME/.install"

div "WINDOW MANAGERS"
# Things to install when choosing awesome
awesomedep="awesome alacritty picom maim xclip pamixer playerctl sxiv"
askinstall awesome
if [ "$answer" != "${answer#[Yy]}" ]; then
	# Set the awesome variable to 1 to indicate that it's installed
	awesome="1"
	for i in $awesomedep; do
		installing "$i"
		sudo xbps-install -y "$i" >> /dev/null
	done
fi

# Things to install when choosing bspwm
bspwmdep="bspwm sxhkd alacritty dunst maim nitrogen pamixer picom playerctl polybar rofi xbacklight xclip"
askinstall bspwm
if [ "$answer" != "${answer#[Yy]}" ]; then
	# Set the bspwm variable to 1 to indicate that it's installed
	bspwm="1"
	for i in $bspwmdep; do
		installing "$i"
		sudo xbps-install -y "$i" >> /dev/null
	done
fi
printf "\n"

div "ADDITIONAL PROGRAMS"
other="firefox gimp mpv sxiv neovim keepassxc OTPClient lxappearance"
for i in $other; do
	askinstall "$i"
	if [ "$answer" != "${answer#[Yy]}" ]; then	
		installing "$i"
		sudo xbps-install -y "$i" >> /dev/null
		printf "\n"
	fi
done

# Fish is seperate so it downloads bat and lsd only when fish is installed
fishdep="fish-shell bat lsd"
askinstall fish
if [ "$answer" != "${answer#[Yy]}" ]; then
	for i in $fishdep; do
		installing "$i"
		sudo xbps-install -y "$i" >> /dev/null
	done
fi
printf "\n"

div "FINISHING TOUCHES"
# The rice uses Hack font so let's download it
installing "Hack font"
sudo xbps-install -y font-hack-ttf >> /dev/null
printf "\n\n"
echo "Updating packages"
sudo xbps-install -Su

div "THE END"
# If the user has downloaded both it asks which wm to use
if [ "$awesome" -eq 1 ] && [ "$bspwm" -eq 1 ]; then
	read -p "Which window manager do you want to use?
	none - 0
	awesome - 1
	bspwm - 2
	" -r answer
	# If user chooses awesome
	if [ "$answer" -eq 1 ]; then
		# If file exists just replace exec line
		if [ -s "$HOME/.xinitrc" ]; then
			sed -i "s/exec.*/exec awesome/" "$HOME/.xinitrc"
		else
			# Add exec line to file if it doesn't exist
			echo "exec awesome" >> "$HOME/.xinitrc"
		fi
	elif [ "$answer" -eq 2 ]; then
		if [ -s "$HOME/.xinitrc" ]; then
			sed -i "s/exec.*/exec bspwm/" "$HOME/.xinitrc"
		else
			echo "exec bspwm" >> "$HOME/.xinitrc"
		fi
	fi
elif [ "$awesome" -eq 1 ]; then
	if [ -s "$HOME/.xinitrc" ]; then
		sed -i "s/exec.*/exec awesome/" "$HOME/.xinitrc"
	else
		echo "exec awesome" >> "$HOME/.xinitrc"
	fi
elif [ "$bspwm" -eq 1 ]; then
	if [ -s "$HOME/.xinitrc" ]; then
		sed -i "s/exec.*/exec bspwm/" "$HOME/.xinitrc"
	else
		echo "exec bspwm" >> "$HOME/.xinitrc"
	fi
fi

# Message about installing Hack Nerd Font
printf "\e[1;31mYou also need to install the Hack Nerd Font!\e[0m
\e[1;33mcurl -O -o Hack.zip \"https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Hack.zip\"\e[0m
To unpack it you maybe also want to use for example: p7zip.
\e[1;33m7z x Hack.zip\e[0m
And move the files of the font to \"\$HOME/.local/share/fonts\".
Do \e[1;33mmkdir \$HOME/.local/share/fonts\e[0m if it doesn't exist.
\e[1;33mmv Hack* \"\$HOME/.local/share/fonts\"\e[0m"
