#!/usr/bin/env sh
# FUNCTIONS
# Install something
install() {	
	for i in $1; do
		printf "\nInstalling \033[32m%s\033[0m" "$i"
		sudo xbps-install -y "$i" >> /dev/null
	done
}

# Install something with asking
installasking() {
	printf "\nDo you want to install \033[32m%s\033[0m? [\033[1;32mY\033[0m/\033[31mN\033[0m] " "$1"
	read -r answer
	if [ "$answer" != "${answer#[Yy]}" ]; then
		install "$2"
	fi
}

# A nice thing to divide stuff into sections
div() {	printf "\n\033[1;32m%s\n\033[0m%s\n------------------------------" "$1" "$2"; }

# Sets the wm
setwm() {
	# If file exists just replace exec line
	if [ -s "$HOME/.xinitrc" ]; then sed -i "s/exec.*/exec $1/" "$HOME/.xinitrc"
		# If file doesn't exist create the file with the exec line
	else echo "exec $1" >> "$HOME/.xinitrc"; fi
}

# THE REAL DEAL
distro=$(lsb_release -s -c)
if [ "$distro" = "void" ]; then
	printf "\033[32mWelcome!\nThis script will download my dotfiles and programs related with it"
else
	printf "\033[31mYour distro isn't supported!"
	exit
fi

div "THINGS THAT ARE REQUIRED" "Everything requires this (the dotfiles/script)" 
install "font-hack-ttf git rcm xorg"
printf "\n"

div "DOTFILES" "Getting the thing"
printf "\nDownloading dotfiles\n"
git clone "https://gitlab.com/cha0t1c/dotfiles.git" "$HOME/.dotfiles" >> /dev/null

printf "\nSymlinking dotfiles\n"
rcup

printf "\nRemoving useless stuff\n"
rm -r "$HOME/.images" "$HOME/.LICENSE" "$HOME/.README.md" "$HOME/.install"

div "WINDOW MANAGER(s)" "Without this you won't have a gui"
# Install bspwm with dependencies
installasking bspwm "bspwm sxhkd alacritty dunst maim nitrogen pamixer picom playerctl polybar rofi xbacklight xclip"
printf "\n"

div "PROGRAMS" "Programs that are in the dotfiles (you probably got most of these if you installed bspwm)"
programs="alacritty dunst neovim picom polybar rofi sxiv"
for i in $programs; do installasking "$i" "$i"; printf "\n"; done

# Fish is seperate so it downloads bat and exa only when fish is installed
installasking fish "fish-shell bat exa" 
printf "\n"

div "ADDITIONAL PROGRAMS" "These aren't in the dotfiles"
other="firefox gimp mpv keepassxc OTPClient lxappearance"
for i in $other; do installasking "$i" "$i"; printf "\n"; done

div "THE END" "The installation is nearly complete"
printf "\nUpdating packages\n"
sudo xbps-install -Su

setwm bspwm	

# Message about installing Hack Nerd Font
printf "\n\033[1;31mYou also need to install the Hack Nerd Font!\033[0m
\033[1;33mcurl -O -o Hack.zip \"https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Hack.zip\"\033[0m
To unpack it you maybe also want to use for example: p7zip.
\033[1;33m7z x Hack.zip\033[0m
And move the files of the font to \"\$HOME/.local/share/fonts\".
Do \033[1;33mmkdir \$HOME/.local/share/fonts\033[0m if it doesn't exist.
\033[1;33mmv Hack* \"\$HOME/.local/share/fonts\"\033[0m"
