= Dotfiles
Cha0t1c <notnotcha0t1c@protonmail.com>
1.0, {docdate}
:toc:

WARNING: You probably _will_ and *must* change something in my dotfiles, I recommend looking through these dotfiles and changing things to fit your setup (things like setting the editor, setting a polish keymap and swapping caps lock with escape etc.).

This repo contains my dotfiles.

It uses https://github.com/thoughtbot/rcm[rcm].

IMPORTANT: You will probably get a quicker response on Gitlab than GitHub

== Contains

* link:config/alacritty/[alacritty]
* link:config/awesome/[awesome]
* link:config/fish/[fish]
* link:config/mpd/[mpd]
* link:config/ncmpcpp[ncmpcpp]
* link:config/nvim/[nvim]
* link:config/sxiv/exec/[sxiv]
* link:config/user-dirs.dirs[xdg dirs]
* link:xinitrc[xinitrc]
* link:Xresources[xresources]
* link:config/zathura/[zathura]
* https://gitlab.com/-/snippets/2054705[/etc/issue]

== Install
Clone the repository
[source,sh]
----
git clone --recurse-submodules https://gitlab.com/cha0t1c/dotfiles.git $HOME/.dotfiles
----

Install https://github.com/thoughtbot/rcm[rcm]

Install the dotfiles
[source,sh]
----
RCRC=$HOME/.dotfiles/rcrc rcup
----

== Dependencies
If something requires something, it will be written in it's README or here.
* Hack (if you didn't install the dotfiles with rcm)
** https://github.com/source-foundry/Hack/releases/download/v3.003/Hack-v3.003-ttf.zip[Hack]
** https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/Hack[Hack Nerd Font]
