require("bar/widgets/taglist")
require("bar/widgets/tasklist")
require("bar/widgets/volume")
require("bar/widgets/battery")
require("bar/widgets/clock")
require("bar/widgets/layoutbox")
require("bar/widgets/menu")
