#+TITLE: [[https://zsh.org][zsh]]
#+AUTHOR: chtc

My simple personal zsh config.

*IMPORTANT: Read through this to see dependencies and other stuff.*

* Table Of Contents :toc:
- [[#aliases][Aliases]]
- [[#what-it-does][What it does]]
- [[#config][Config]]
  - [[#zshenv][.zshenv]]
  - [[#zprofile][.zprofile]]
  - [[#zshrc][.zshrc]]

* Aliases
| Alias  | What it does                                           |
|--------+--------------------------------------------------------|
| e      | Launch editor (emacs)                                  |
| se     | Launch editor with doas (emacs)                        |
| ls     | Use [[https://github.com/ogham/exa][exa]] instead of ls                                  |
| lsa    | Show hidden files (exa)                                |
| lsl    | Show files with extended info (exa)                    |
| lsla   | Show extended info and hidden files (exa)              |
| rm     | Move file to trash can (trash-cli)                     |
| rme    | Empty trash can (trash-cli)                            |
| rml    | List files in trash can (trash-cli)                    |
| rmr    | Restore file(s) from trash can (trash-cli)             |
| xi     | Install package(s) (xbps)                              |
| xif    | View and install packages (xbps, fzf)                  |
| xr     | Remove package(s) (xbps)                               |
| xrf    | View and remove installed packages (xbps, fzf)         |
| xu     | Update packages (xbps)                                 |
| xc     | Clean cache and remove orphans (xbps)                  |
| adf    | View adoc document as a pdf (asciidoctor-pdf, zathura) |
| setwal | Set wallpaper in AwesomeWm (my config)                 |

* What it does
- Sets some variables
  - BROWSER to ~firefox~
  - EDITOR to ~emacs~
  - VISUAL to ~$EDITOR~
  - PAGER to ~less~
  - TERM to ~alacritty~
  - WM to ~awesome~
  - Some fzf options
- Cleaning up the home directory
  - XDG
    - XDG_CACHE_HOME to ~~/.cache~
    - XDG_CONFIG_HOME to ~~/.config~
    - XDG_DATA_HOME to ~~/.local/share~
  - XINITRC to ~$XDG_CONFIG_HOME/X11/xinitrc~
  - XSERVERRC to ~$XDG_CONFIG_HOME/X11/xserverrc~
  - GEM_PATH to ~$XDG_DATA_HOME/gem~
  - GEM_HOME to ~$XDG_DATA_HOME/gem~
  - GEM_SPEC_CACHE to ~$XDG_CACHE_HOME/gem~
  - GNUPGHOME to ~$XDG_DATA_HOME/gnupg~
  - GTK2_RC_FILES to ~$XDG_CONFIG_HOME/gtk-2.0/gtkrc~
  - INPUTRC to ~$XDG_CONFIG_HOME/readline/inputrc~
  - EMACSDIR to ~$XDG_CONFIG_HOME/emacs~
  - DOOMDIR to ~$XDG_CONFIG_HOME/doom~
  - DOOMLOCALDIR to ~$DOOMDIR/local~
  - HISTFILE to ~$XDG_DATA_HOME/zsh/history~
  - LIBERICA_DIR to ~$HOME/.local/bin/jdk8u292-full~
  - ZDOTDIR to ~$XDG_CONFIG_HOME/zsh~
  - Disabling the less history file
  - zcompdumps are placed in ~$XDG_CACHE_HOME/zsh~
- PATH
  - ~$HOME/.local/bin~
  - ~$GEM_HOME/bin~
  - ~$XDG_CONFIG_HOME/emacs/bin~
- Makes gpg2 work
- Minimal prompt
- Completion
- Syntax highlighting
- Auto-suggestions
- Vi keybindings
- Cursor changes based on vi mode
- Entering the directory just by entering the path.
- Launch

* Config
** .zshenv
I set variables in this file, it is sourced every time.
#+BEGIN_SRC shell :tangle ~/.dotfiles/zsh/.zshenv
# Set some XDG stuff
export XDG_DATA_HOME=${XDG_DATA_HOME:="$HOME/.local/share"}
export XDG_CACHE_HOME=${XDG_CACHE_HOME:="$HOME/.cache"}
export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:="$HOME/.config"}

# Set zsh config directory
export ZDOTDIR=${ZDOTDIR:="$XDG_CONFIG_HOME/zsh"}

# Clean up ~/
export XINITRC="$XDG_CONFIG_HOME/X11/xinitrc"
export XSERVERRC="$XDG_CONFIG_HOME/X11/xserverrc"
export GEM_PATH="$XDG_DATA_HOME/gem"
export GEM_HOME="$XDG_DATA_HOME/gem"
export GEM_SPEC_CACHE="$XDG_CACHE_HOME/gem"
export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc"
export INPUTRC="$XDG_CONFIG_HOME/readline/inputrc"
export EMACSDIR="$XDG_CONFIG_HOME/emacs"
export DOOMDIR="$XDG_CONFIG_HOME/doom"
export DOOMLOCALDIR="$DOOMDIR/local"
export LESSHISTFILE=-

# Default apps
export BROWSER=firefox
export EDITOR=emacs
export VISUAL="$EDITOR"
export PAGER=less
export WM=awesome

export FZF_DEFAULT_OPTS="-m --color '16,bg+:-1,border:8' --border sharp --preview-window sharp:wrap --layout=reverse-list --info inline"

export LIBERICA_DIR="$HOME/.local/bin/jdk8u292-full"

# Set path
typeset -U path
path+="$HOME/.local/bin:$GEM_HOME/bin:$XDG_CONFIG_HOME/emacs/bin:$LIBERICA_DIR/bin"
#+END_SRC

** .zprofile
I use this file to launch X11, it is read at login before .zshrc.
#+BEGIN_SRC shell :tangle ~/.dotfiles/zsh/.config/zsh/.zprofile
if [[ "$(tty)" = "/dev/tty1" ]]; then
    pgrep "$WM" || startx ${XINITRC:="$HOME/.xinitrc"}
fi
#+END_SRC

** .zshrc
The main thing.
#+BEGIN_SRC shell :tangle ~/.dotfiles/zsh/.config/zsh/.zshrc
autoload colors && colors
autoload -Uz compinit
#+END_SRC

*** Exports
#+BEGIN_SRC shell :tangle ~/.dotfiles/zsh/.config/zsh/.zshrc
HISTFILE="$XDG_CONFIG_HOME/zsh/history"
HISTSIZE=10000
SAVEHIST=10000
setopt INC_APPEND_HISTORY_TIME

compinit -d $XDG_CACHE_HOME/zsh/zcompdump-$ZSH_VERSION

# Prompt
PS1="%F{cyan}%~ %(?.%F{green}.%F{red})>%F{normal} "
#+END_SRC

*** Aliases
#+BEGIN_SRC shell :tangle ~/.dotfiles/zsh/.config/zsh/.zshrc
# editor
alias e="$EDITOR"
alias se="doas -E $EDITOR"

# ls
alias ls="exa --icons --group-directories-first"
alias lsa="exa -a --icons --group-directories-first"
alias lsl="exa -a -l --git --icons --group-directories-first"
alias lsla="exa -a -l --git --icons --group-directories-first"

# trash
alias rm="trash-put"
alias rme="trash-empty"
alias rml="trash-list"
alias rmr="trash-restore"

# xbps
alias xi="doas xbps-install -S"
xif() {
    xbps-query -Rs . --regex | cut -d " " -f 2 | fzf -q "$1" --preview "xbps-query -RS {1}" | xargs -ro doas xbps-install -S
}
alias xr="doas xbps-remove -R"
xrf() {
    xbps-query -l | cut -d " " -f 1,2 | fzf -q "$1" --preview "xbps-query -RS {2}" | cut -d " " -f 2 | xargs -ro doas xbps-remove -R
}
alias xu="doas xbps-install -Su"
alias xc="doas xbps-remove -Oo"

# other
adf() {
    asciidoctor-pdf -o - $1 | zathura -
}
alias bat="bat --theme ansi"
setwal() {
    cp $1 "$XDG_CONFIG_HOME/awesome/wall.png"
}
smn() {
    apropos . | cut -d "(" -f 1 | cut -d "," -f 1 | fzf --multi -q "$1" --preview "man {1}" | xargs -ro man
}
#+END_SRC

*** Other
#+BEGIN_SRC shell :tangle ~/.dotfiles/zsh/.config/zsh/.zshrc
# Completion
zstyle ':completion:*' menu select
zmodload zsh/complist
compinit
_comp_options+=(globdots)

# Vi keys
bindkey -v

# Use vi keys in tab complete menu
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
bindkey -M menuselect 'j' vi-down-line-or-history
bindkey -v '^?' backward-delete-char

# Vi cursor
# Change cursor shape for different vi modes.
function zle-keymap-select () {
    case $KEYMAP in
        vicmd) echo -ne '\e[1 q';;      # block
        viins|main) echo -ne '\e[5 q';; # beam
    esac
}
zle -N zle-keymap-select
zle-line-init() {
    echo -ne "\e[5 q"
}
zle -N zle-line-init
echo -ne '\e[5 q'                # Use beam shape cursor on startup.
preexec() { echo -ne '\e[5 q' ;} # Use beam shape cursor for each new prompt.

# Enter directory by just typing path
setopt autocd
#+END_SRC

*** Plugins
#+BEGIN_SRC shell :tangle ~/.dotfiles/zsh/.config/zsh/.zshrc
# Autosuggestions
source "$XDG_CONFIG_HOME/zsh/asg/zsh-autosuggestions.zsh"

# Syntax highlighting
source "$XDG_CONFIG_HOME/zsh/fsh/fast-syntax-highlighting.plugin.zsh"
#+END_SRC
