#! /bin/sh
## AUTOSTART ##
pgrep -x sxhkd > /dev/null || sxhkd &
nitrogen --restore &
$HOME/.config/polybar/launch.sh &
pgrep -x picom || picom -b --experimental-backends &
xsetroot -cursor_name left_ptr &

## MONITOR ##
bspc monitor -d I II III IV V VI VII VIII IX X

## CONFIG STUFF ##
bspc config border_width         2
bspc config window_gap           7
bspc config bottom_padding       0
bspc config top_padding         25

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#53d6c7"
bspc config active_border_color "#dbb32d"
bspc config focused_border_color "#ebc13d"
bspc config presel_feedback_color "#fd9456"

## RULES ##
bspc rule -a Firefox desktop='^1'
bspc rule -a Alacritty desktop='^2'
bspc rule -a Gimp desktop='^3' state=floating
bspc rule -a kdenlive desktop='^3' state=floating
bspc rule -a Mpv desktop='^4' state=floating
bspc rule -a discord state=floating
bspc rule -a KeePassXC state=floating
