#! /bin/sh
## AUTOSTART ##
pgrep -x sxhkd > /dev/null || sxhkd &
nitrogen --restore &
$HOME/.config/polybar/launch.sh &
dunst &
picom &
xsetroot -cursor_name left_ptr &

## MONITOR ##
bspc monitor -d I II III IV V VI VII VIII IX X

## CONFIG STUFF ##
bspc config border_width         2
bspc config window_gap          10
bspc config bottom_padding       0
bspc config top_padding         30

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#325b66"
bspc config active_border_color "#f275be"
bspc config focused_border_color "#ff84cd"
bspc config presel_feedback_color "#ff665c"

## RULES ##
#bspc rule -a Gimp state=floating follow=on
bspc rule -a Mpv state=floating
bspc rule -a discord state=floating
bspc rule -a KeePassXC state=floating
