#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh &
dunst &
xsetroot -cursor_name left_ptr &
nitrogen --restore &
picom &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          10
bspc config top_padding         35

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#4d4d4d"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#caa9fa"
bspc config presel_feedback_color "#ff79c6"

bspc rule -a Gimp state=floating follow=on
bspc rule -a Mpv state=floating
bspc rule -a discord state=floating
