#!/bin/sh
while read file
do
    case "$1" in
        "C-d")
            trash-put "$file" ;;
        "C-w")
#            cp "$file" "$XDG_CONFIG_HOME/awesome/wall.png" ;;
            hsetroot -cover "$file" -write "$XDG_CACHE_HOME/wall.png" ;;
    esac
done
