#!/bin/sh

launch() {
    pgrep -x "$1" -u $USER > /dev/null || $@ &
}

launch xrdb -load "$XDG_CONFIG_HOME"/X11/Xresources
launch setxkbmap -option "caps:swapescape"
launch hsetroot -cover "$XDG_CONFIG_HOME"/berry/wall.png
launch pulseaudio --start
launch sxhkd -c "$XDG_CONFIG_HOME"/berry/sxhkdrc -m 1
launch dunst
"$XDG_CONFIG_HOME"/polybar/launch-polybar &

# Set decoration geometry
berryc border_width       0
berryc inner_border_width 0
berryc title_height       18
berryc edge_gap           6 32 6 6

# Set decoration colors
berryc focus_color         002b36
berryc unfocus_color       002b36
berryc inner_focus_color   859900
berryc inner_unfocus_color 073642
berryc text_focus_color    002b36
berryc text_unfocus_color  839496

# Other options
berryc smart_place "true"
berryc draw_text   "true"
berryc edge_lock   "true"
berryc set_font    "Iosevka-Aile-11"

berryc move_mask   "mod5"
berryc resize_mask "mod1"

berryc name_desktop 0 "1"
berryc name_desktop 1 "2"
berryc name_desktop 2 "3"
berryc name_desktop 3 "4"
berryc name_desktop 4 "5"
berryc name_desktop 5 "6"
berryc name_desktop 6 "7"
berryc name_desktop 7 "8"
berryc name_desktop 8 "9"
berryc name_desktop 9 "10"
