#+TITLE: Emacs Config
#+AUTHOR: Cha0t1c
#+PROPERTY: header-args :tangle config.el

This is my [[https://github.com/hlissner/doom-emacs/][Doom Emacs]] config.

* Table of contents :toc:
- [[#looks][Looks]]
  - [[#font][Font]]
  - [[#theme][Theme]]
- [[#other][Other]]
  - [[#org][Org]]
  - [[#line-numbers][Line Numbers]]

* Looks
** Font
Doom exposes five (optional) variables for controlling fonts in Doom. Here are the three important ones:
+ `doom-font'
+ `doom-variable-pitch-font'
+ `doom-big-font' -- used for `doom-big-font-mode'; use this for presentations or streaming.
They all accept either a font-spec, font string ("Input Mono-12"), or xlfd font string. You generally only need these two:
#+BEGIN_SRC emacs-lisp
(setq doom-font (font-spec :family "monospace" :size 14)
       doom-variable-pitch-font (font-spec :family "monospace" :size 13))
#+END_SRC

** Theme
There are two ways to load a theme. Both assume the theme is installed and available. You can either set `doom-theme' or manually load a theme with the `load-theme' function.
#+BEGIN_SRC emacs-lisp
(setq doom-theme 'doom-gruvbox)
#+END_SRC

* Other
** Org
If you use `org' and don't want your org files in the default location below, change `org-directory'. It must be set before org loads!
#+BEGIN_SRC emacs-lisp
(setq org-directory "~/org/")
#+END_SRC

** Line Numbers
This determines the style of line numbers in effect. If set to `nil', line numbers are disabled. For relative line numbers, set this to `relative'.
#+BEGIN_SRC emacs-lisp
(setq display-line-numbers-type 'relative)
#+END_SRC
