#! /bin/sh

sxhkd &
wal -R &
dbus-launch compton -CG --config ~/.config/compton.conf &
~/.config/polybar/launch.sh &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          7

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
# Use the line below if you are on bspwm >= 0.9.4
#bspc config presel_feedback_color "$color1"
# Use the line below if you are on bspwm < 0.9.4
bspc config presel_border_color "$color1"

bspc rule -a Gimp state=floating follow=on
bspc rule -a Steam state=floating follow=on
bspc rule -a discord desktop=^2
